import { Metadata } from "next";

export const metadata: Metadata = {
  title: "SEO Pricing Page",
  description: "Generated by create next app",
};


export default function ContactPage(){
    return (
        <>
        <span className= "text-4xl">Pricing Page</span>
        </>
    )
}