import { Metadata } from "next";

export const metadata: Metadata = {
  title: "SEO Contac Page",
  description: "Generated by create next app",
};

export default function ContactPage(){
    return (
        <>
        <span className= "text-4xl">Contact Page</span>
        </>
    )
}