import type { Metadata } from "next";
 // There are different methods to set the metadata of a page,
 // this is one but we can also set the metadata from the database, or we can set it in the layout of the page, etc.
export const metadata: Metadata = {
  title: "SEO About Page",
  description: "Generated by create next app",
};

export default function AboutPage(){
    return (
        <main className="flex flex-col items-center p-24">
        <span className="mb-12 text-2xl font-bold">This is the about page</span>
        <span className= "text-4xl">About Page</span>
        </main>
    )
}